"""로컬 개발용 하드코딩 더미 데이터.

이 파일은 DB에 직접 접근하지 않는다.
`user_key`, `team_key`, `board_key`, `post_key`는 seed 과정에서 row를 연결하기
위한 내부 식별자이며 실제 DB 컬럼으로 저장하지 않는다.

데이터 규모:
- 3개 반: 301, 302, 303
- 반별 2팀
- 팀당 4명
- 팀마다 게시판 1개, 게시글 3개, 댓글 3개, 주간 요약 1개
"""

from __future__ import annotations

EXPECTED_CLASSROOMS = (301, 302, 303)
EXPECTED_TEAMS_PER_CLASSROOM = 2
EXPECTED_MEMBERS_PER_TEAM = 4
EXPECTED_WEEK = 1

POST_CATEGORIES = ("학습 기록", "질문", "회고")

USERS = [
    {"key": "u30101", "name": "김민재", "phone_num": "010-3010-1001", "classroom": 301},
    {"key": "u30102", "name": "이서윤", "phone_num": "010-3010-1002", "classroom": 301},
    {"key": "u30103", "name": "박도현", "phone_num": "010-3010-1003", "classroom": 301},
    {"key": "u30104", "name": "최하린", "phone_num": "010-3010-1004", "classroom": 301},
    {"key": "u30105", "name": "정유찬", "phone_num": "010-3010-1005", "classroom": 301},
    {"key": "u30106", "name": "한지우", "phone_num": "010-3010-1006", "classroom": 301},
    {"key": "u30107", "name": "오세진", "phone_num": "010-3010-1007", "classroom": 301},
    {"key": "u30108", "name": "강나연", "phone_num": "010-3010-1008", "classroom": 301},
    {"key": "u30201", "name": "윤태준", "phone_num": "010-3020-1001", "classroom": 302},
    {"key": "u30202", "name": "장서현", "phone_num": "010-3020-1002", "classroom": 302},
    {"key": "u30203", "name": "임준서", "phone_num": "010-3020-1003", "classroom": 302},
    {"key": "u30204", "name": "신예린", "phone_num": "010-3020-1004", "classroom": 302},
    {"key": "u30205", "name": "조민호", "phone_num": "010-3020-1005", "classroom": 302},
    {"key": "u30206", "name": "배수빈", "phone_num": "010-3020-1006", "classroom": 302},
    {"key": "u30207", "name": "백준영", "phone_num": "010-3020-1007", "classroom": 302},
    {"key": "u30208", "name": "문가은", "phone_num": "010-3020-1008", "classroom": 302},
    {"key": "u30301", "name": "고현우", "phone_num": "010-3030-1001", "classroom": 303},
    {"key": "u30302", "name": "유다인", "phone_num": "010-3030-1002", "classroom": 303},
    {"key": "u30303", "name": "남시우", "phone_num": "010-3030-1003", "classroom": 303},
    {"key": "u30304", "name": "서지민", "phone_num": "010-3030-1004", "classroom": 303},
    {"key": "u30305", "name": "권도윤", "phone_num": "010-3030-1005", "classroom": 303},
    {"key": "u30306", "name": "황은서", "phone_num": "010-3030-1006", "classroom": 303},
    {"key": "u30307", "name": "송하준", "phone_num": "010-3030-1007", "classroom": 303},
    {"key": "u30308", "name": "안채원", "phone_num": "010-3030-1008", "classroom": 303},
]

STUDENT_PROFILES = [
    {
        "user_key": "u30101",
        "project_count": 4,
        "score": 88,
        "interests": "RAG 검색 품질 개선과 백엔드 API 설계",
        "self_intro": "FastAPI로 CRUD API를 여러 번 구현했고, 이번에는 검색 근거가 명확한 게시판을 만들어보고 싶습니다.",
        "avoid_condition": "밤 11시 이후 회의는 어렵습니다.",
    },
    {
        "user_key": "u30102",
        "project_count": 2,
        "score": 74,
        "interests": "사용자 흐름 정리와 학습 기록 UX",
        "self_intro": "기능을 작게 나누고 화면 흐름을 문서로 정리하는 편입니다. 게시판 사용성이 좋은 팀을 만들고 싶습니다.",
        "avoid_condition": "발표를 단독으로 맡는 것은 부담스럽습니다.",
    },
    {
        "user_key": "u30103",
        "project_count": 3,
        "score": 82,
        "interests": "SQLAlchemy 관계 설계와 테스트 자동화",
        "self_intro": "DB 모델을 먼저 안정적으로 잡고 테스트로 깨지는 지점을 찾는 작업을 선호합니다.",
        "avoid_condition": "요구사항이 자주 바뀌면 기록을 남기고 합의한 뒤 진행하고 싶습니다.",
    },
    {
        "user_key": "u30104",
        "project_count": 1,
        "score": 63,
        "interests": "AI 기능을 서비스에 연결하는 전체 흐름",
        "self_intro": "AI API 사용 경험은 적지만 학습 속도가 빠르고 모르는 부분을 질문으로 정리하는 데 익숙합니다.",
        "avoid_condition": "주말 오전 일정은 어렵습니다.",
    },
    {
        "user_key": "u30105",
        "project_count": 5,
        "score": 91,
        "interests": "팀 운영 자동화와 주간 학습 요약",
        "self_intro": "이전 프로젝트에서 일정 관리와 백엔드 배포를 맡았습니다. 이번에는 팀 요약 기능을 안정적으로 만들고 싶습니다.",
        "avoid_condition": "프론트엔드 단독 구현은 피하고 싶습니다.",
    },
    {
        "user_key": "u30106",
        "project_count": 2,
        "score": 70,
        "interests": "게시글 분류와 질문 데이터 정리",
        "self_intro": "질문을 구조화하고 회의 내용을 정리하는 일을 잘합니다. RAG가 참고할 데이터를 깔끔하게 쌓고 싶습니다.",
        "avoid_condition": "즉흥적인 역할 변경은 어렵습니다.",
    },
    {
        "user_key": "u30107",
        "project_count": 3,
        "score": 79,
        "interests": "벡터DB 메타데이터 필터와 검색 실험",
        "self_intro": "검색 결과가 왜 달라지는지 비교 실험하는 것을 좋아합니다. Chroma 필터링을 집중적으로 보고 싶습니다.",
        "avoid_condition": "긴 회의보다 짧은 체크인을 선호합니다.",
    },
    {
        "user_key": "u30108",
        "project_count": 1,
        "score": 66,
        "interests": "학습 회고 작성과 팀 문서 품질",
        "self_intro": "개발 경험은 많지 않지만 회고와 문서화를 꾸준히 할 수 있습니다. 팀의 진행 상황을 놓치지 않겠습니다.",
        "avoid_condition": "복잡한 인프라 작업은 멘토 도움을 받고 싶습니다.",
    },
    {
        "user_key": "u30201",
        "project_count": 4,
        "score": 86,
        "interests": "FastAPI 서비스 구조와 인증 흐름",
        "self_intro": "API 라우터와 DB 세션 관리를 맡아본 경험이 있습니다. 이번에는 게시판 권한 구조를 명확히 잡고 싶습니다.",
        "avoid_condition": "새벽 작업은 어렵습니다.",
    },
    {
        "user_key": "u30202",
        "project_count": 2,
        "score": 73,
        "interests": "AI 요약 결과를 운영자가 읽기 좋게 만드는 방식",
        "self_intro": "사용자에게 보이는 문장을 다듬는 데 관심이 있습니다. 요약 결과를 신뢰할 수 있게 표현하고 싶습니다.",
        "avoid_condition": "회의록 없이 구두로만 결정하는 방식은 피하고 싶습니다.",
    },
    {
        "user_key": "u30203",
        "project_count": 3,
        "score": 81,
        "interests": "데이터 검증과 seed 데이터 품질",
        "self_intro": "테스트 데이터가 현실적이어야 기능을 제대로 확인할 수 있다고 생각합니다. 검증 로직을 꼼꼼히 보겠습니다.",
        "avoid_condition": "마감 직전 큰 구조 변경은 피하고 싶습니다.",
    },
    {
        "user_key": "u30204",
        "project_count": 1,
        "score": 62,
        "interests": "팀 게시판의 질문/답변 흐름",
        "self_intro": "질문을 잘 정리하고 답변을 문서로 남기는 편입니다. 학습 게시판을 실제로 쓰기 좋게 만들고 싶습니다.",
        "avoid_condition": "혼자 오래 막히는 상황은 피하고 싶습니다.",
    },
    {
        "user_key": "u30205",
        "project_count": 5,
        "score": 94,
        "interests": "RAG 파이프라인과 문서 청킹 전략",
        "self_intro": "임베딩, 청킹, 검색 결과 비교에 관심이 많습니다. 근거가 명확한 답변 생성을 구현하고 싶습니다.",
        "avoid_condition": "프롬프트만으로 해결하는 방식은 선호하지 않습니다.",
    },
    {
        "user_key": "u30206",
        "project_count": 2,
        "score": 71,
        "interests": "팀별 학습 키워드 추출",
        "self_intro": "게시글에서 핵심 키워드와 막힌 지점을 뽑아내는 기능에 관심이 있습니다.",
        "avoid_condition": "평일 오전 회의는 어렵습니다.",
    },
    {
        "user_key": "u30207",
        "project_count": 3,
        "score": 84,
        "interests": "PostgreSQL 스키마와 관계 제약",
        "self_intro": "unique 제약과 외래키 관계를 명확히 잡는 작업을 좋아합니다. 데이터 무결성을 우선해서 보겠습니다.",
        "avoid_condition": "DB를 직접 수정할 때는 사전 합의가 필요합니다.",
    },
    {
        "user_key": "u30208",
        "project_count": 1,
        "score": 67,
        "interests": "회고 데이터 기반 학습 개선",
        "self_intro": "팀이 무엇을 배웠고 어디서 막혔는지 기록하는 데 관심이 있습니다. 회고를 꾸준히 남기겠습니다.",
        "avoid_condition": "발표 자료 제작을 혼자 맡기는 것은 어렵습니다.",
    },
    {
        "user_key": "u30301",
        "project_count": 4,
        "score": 89,
        "interests": "백엔드 API와 RAG 검색 API 연결",
        "self_intro": "서비스 레이어를 분리하고 API 응답 구조를 일정하게 맞추는 작업을 선호합니다.",
        "avoid_condition": "기획 없이 바로 구현부터 시작하는 방식은 피하고 싶습니다.",
    },
    {
        "user_key": "u30302",
        "project_count": 2,
        "score": 72,
        "interests": "게시글 카테고리와 검색 필터",
        "self_intro": "게시글을 카테고리별로 관리하고 필터링하는 기능에 관심이 있습니다.",
        "avoid_condition": "주말 저녁 회의는 어렵습니다.",
    },
    {
        "user_key": "u30303",
        "project_count": 3,
        "score": 80,
        "interests": "테스트 코드와 API 문서화",
        "self_intro": "테스트를 먼저 돌려보고 실패 이유를 추적하는 것을 좋아합니다. API 사용법도 같이 정리하고 싶습니다.",
        "avoid_condition": "문서 없이 코드만 공유되는 상황은 피하고 싶습니다.",
    },
    {
        "user_key": "u30304",
        "project_count": 1,
        "score": 65,
        "interests": "학습 자료 공유와 팀 지식 축적",
        "self_intro": "좋은 자료를 찾아 공유하고 팀 문서로 정리하는 일을 꾸준히 할 수 있습니다.",
        "avoid_condition": "너무 빠른 진행보다 이해를 확인하며 가고 싶습니다.",
    },
    {
        "user_key": "u30305",
        "project_count": 5,
        "score": 95,
        "interests": "요약 품질 평가와 운영자 대시보드",
        "self_intro": "AI 결과를 그대로 믿기보다 근거와 누락을 확인하는 흐름을 만들고 싶습니다.",
        "avoid_condition": "검증 없는 자동화는 피하고 싶습니다.",
    },
    {
        "user_key": "u30306",
        "project_count": 2,
        "score": 76,
        "interests": "학생 프로필 기반 팀 추천",
        "self_intro": "관심사와 프로젝트 경험을 조합해 납득 가능한 팀 추천 이유를 만들고 싶습니다.",
        "avoid_condition": "늦은 밤 장시간 페어 작업은 어렵습니다.",
    },
    {
        "user_key": "u30307",
        "project_count": 3,
        "score": 83,
        "interests": "데이터 삭제/수정 시 벡터 인덱스 동기화",
        "self_intro": "게시글 수정 시 RAG 문서도 같이 갱신되는 구조에 관심이 있습니다.",
        "avoid_condition": "수동으로 반복 작업하는 흐름은 줄이고 싶습니다.",
    },
    {
        "user_key": "u30308",
        "project_count": 1,
        "score": 68,
        "interests": "질문 모음과 멘토 피드백 정리",
        "self_intro": "팀에서 자주 나오는 질문을 모아 멘토가 보기 좋게 정리하고 싶습니다.",
        "avoid_condition": "처음부터 큰 범위를 맡기보다는 작은 기능부터 맡고 싶습니다.",
    },
]

TEAMS = [
    {"key": "w1-c301-t1", "week": 1, "classroom": 301, "team_num": 1, "name": "301반 1주차 1팀 그린필드"},
    {"key": "w1-c301-t2", "week": 1, "classroom": 301, "team_num": 2, "name": "301반 1주차 2팀 벡터웨이"},
    {"key": "w1-c302-t1", "week": 1, "classroom": 302, "team_num": 1, "name": "302반 1주차 1팀 로그북"},
    {"key": "w1-c302-t2", "week": 1, "classroom": 302, "team_num": 2, "name": "302반 1주차 2팀 리트리버"},
    {"key": "w1-c303-t1", "week": 1, "classroom": 303, "team_num": 1, "name": "303반 1주차 1팀 컨텍스트"},
    {"key": "w1-c303-t2", "week": 1, "classroom": 303, "team_num": 2, "name": "303반 1주차 2팀 메타데이터"},
]

TEAM_MEMBERS = [
    {"team_key": "w1-c301-t1", "user_key": "u30101"},
    {"team_key": "w1-c301-t1", "user_key": "u30102"},
    {"team_key": "w1-c301-t1", "user_key": "u30103"},
    {"team_key": "w1-c301-t1", "user_key": "u30104"},
    {"team_key": "w1-c301-t2", "user_key": "u30105"},
    {"team_key": "w1-c301-t2", "user_key": "u30106"},
    {"team_key": "w1-c301-t2", "user_key": "u30107"},
    {"team_key": "w1-c301-t2", "user_key": "u30108"},
    {"team_key": "w1-c302-t1", "user_key": "u30201"},
    {"team_key": "w1-c302-t1", "user_key": "u30202"},
    {"team_key": "w1-c302-t1", "user_key": "u30203"},
    {"team_key": "w1-c302-t1", "user_key": "u30204"},
    {"team_key": "w1-c302-t2", "user_key": "u30205"},
    {"team_key": "w1-c302-t2", "user_key": "u30206"},
    {"team_key": "w1-c302-t2", "user_key": "u30207"},
    {"team_key": "w1-c302-t2", "user_key": "u30208"},
    {"team_key": "w1-c303-t1", "user_key": "u30301"},
    {"team_key": "w1-c303-t1", "user_key": "u30302"},
    {"team_key": "w1-c303-t1", "user_key": "u30303"},
    {"team_key": "w1-c303-t1", "user_key": "u30304"},
    {"team_key": "w1-c303-t2", "user_key": "u30305"},
    {"team_key": "w1-c303-t2", "user_key": "u30306"},
    {"team_key": "w1-c303-t2", "user_key": "u30307"},
    {"team_key": "w1-c303-t2", "user_key": "u30308"},
]

BOARDS = [
    {"key": "board-w1-c301-t1", "team_key": "w1-c301-t1", "board_name": "그린필드 학습 게시판"},
    {"key": "board-w1-c301-t2", "team_key": "w1-c301-t2", "board_name": "벡터웨이 학습 게시판"},
    {"key": "board-w1-c302-t1", "team_key": "w1-c302-t1", "board_name": "로그북 학습 게시판"},
    {"key": "board-w1-c302-t2", "team_key": "w1-c302-t2", "board_name": "리트리버 학습 게시판"},
    {"key": "board-w1-c303-t1", "team_key": "w1-c303-t1", "board_name": "컨텍스트 학습 게시판"},
    {"key": "board-w1-c303-t2", "team_key": "w1-c303-t2", "board_name": "메타데이터 학습 게시판"},
]

POSTS = [
    {
        "key": "post-w1-c301-t1-study",
        "board_key": "board-w1-c301-t1",
        "author_user_key": "u30101",
        "category": "학습 기록",
        "post_title": "RAG 검색 API 초안 정리",
        "content": "오늘은 게시글과 학생 프로필을 Document로 바꾸는 기준을 정했습니다. post_id, board_id, category를 metadata에 넣기로 했고, 검색 결과에는 원문 출처를 같이 반환하기로 했습니다.",
        "created_at": "2026-06-01T09:20:00+00:00",
    },
    {
        "key": "post-w1-c301-t1-question",
        "board_key": "board-w1-c301-t1",
        "author_user_key": "u30103",
        "category": "질문",
        "post_title": "게시글 수정 시 벡터 문서 갱신 방식",
        "content": "게시글이 수정되면 기존 벡터 문서를 삭제하고 다시 넣는 방식이 안전할지 궁금합니다. source_type, source_id, chunk_index 조합으로 추적하면 될 것 같습니다.",
        "created_at": "2026-06-01T14:10:00+00:00",
    },
    {
        "key": "post-w1-c301-t1-retro",
        "board_key": "board-w1-c301-t1",
        "author_user_key": "u30102",
        "category": "회고",
        "post_title": "첫 회의 회고",
        "content": "팀원이 각자 잘하는 부분을 공유하니 역할을 정하지 않아도 자연스럽게 작업 영역이 나뉘었습니다. 다음 회의부터 결정 사항을 게시판에 남기기로 했습니다.",
        "created_at": "2026-06-01T18:30:00+00:00",
    },
    {
        "key": "post-w1-c301-t2-study",
        "board_key": "board-w1-c301-t2",
        "author_user_key": "u30107",
        "category": "학습 기록",
        "post_title": "Chroma metadata filter 실험",
        "content": "board_id와 category를 조건으로 걸었을 때 검색 결과가 꽤 안정적으로 좁혀졌습니다. 다만 질문 글과 회고 글을 함께 검색할 때는 query 문장을 더 구체화해야 했습니다.",
        "created_at": "2026-06-02T10:00:00+00:00",
    },
    {
        "key": "post-w1-c301-t2-question",
        "board_key": "board-w1-c301-t2",
        "author_user_key": "u30106",
        "category": "질문",
        "post_title": "회고 글도 RAG에 넣어야 할까?",
        "content": "회고에는 감정적인 표현도 많아서 검색 품질에 영향을 줄 수 있을 것 같습니다. 그래도 막힌 지점이 잘 드러나서 요약에는 필요해 보입니다.",
        "created_at": "2026-06-02T15:15:00+00:00",
    },
    {
        "key": "post-w1-c301-t2-retro",
        "board_key": "board-w1-c301-t2",
        "author_user_key": "u30105",
        "category": "회고",
        "post_title": "검색 결과 디버깅 회고",
        "content": "검색 결과가 이상할 때 임베딩 문제로만 보지 말고 원문 청크와 metadata를 먼저 확인해야 한다는 점을 배웠습니다.",
        "created_at": "2026-06-02T19:00:00+00:00",
    },
    {
        "key": "post-w1-c302-t1-study",
        "board_key": "board-w1-c302-t1",
        "author_user_key": "u30201",
        "category": "학습 기록",
        "post_title": "게시판 API 응답 구조 합의",
        "content": "게시글 목록 응답에는 id, category, title, author_id, created_at만 먼저 내려주고 상세 조회에서 content와 comments를 포함하기로 했습니다.",
        "created_at": "2026-06-03T09:40:00+00:00",
    },
    {
        "key": "post-w1-c302-t1-question",
        "board_key": "board-w1-c302-t1",
        "author_user_key": "u30204",
        "category": "질문",
        "post_title": "댓글도 별도 Document로 저장할지",
        "content": "댓글은 짧지만 질문의 맥락을 보완하는 경우가 많습니다. 댓글만 따로 검색되면 맥락이 부족할 수 있어서 post_id metadata가 중요할 것 같습니다.",
        "created_at": "2026-06-03T13:25:00+00:00",
    },
    {
        "key": "post-w1-c302-t1-retro",
        "board_key": "board-w1-c302-t1",
        "author_user_key": "u30202",
        "category": "회고",
        "post_title": "응답 포맷 회고",
        "content": "처음부터 모든 필드를 내려주기보다 화면에서 필요한 데이터만 정리하니 API 설계가 단순해졌습니다.",
        "created_at": "2026-06-03T18:05:00+00:00",
    },
    {
        "key": "post-w1-c302-t2-study",
        "board_key": "board-w1-c302-t2",
        "author_user_key": "u30205",
        "category": "학습 기록",
        "post_title": "청크 크기 비교 실험",
        "content": "300자 단위 청크는 검색 결과가 세밀하지만 문맥이 끊겼고, 700자 단위 청크는 요약에는 좋지만 질문 검색에는 조금 둔했습니다.",
        "created_at": "2026-06-04T10:30:00+00:00",
    },
    {
        "key": "post-w1-c302-t2-question",
        "board_key": "board-w1-c302-t2",
        "author_user_key": "u30207",
        "category": "질문",
        "post_title": "RagDocument에 content_hash가 꼭 필요한가",
        "content": "원문이 바뀌었는지 확인하려면 content_hash가 있으면 좋을 것 같습니다. 다만 MVP에서는 삭제 후 재삽입만으로도 충분한지 고민됩니다.",
        "created_at": "2026-06-04T14:00:00+00:00",
    },
    {
        "key": "post-w1-c302-t2-retro",
        "board_key": "board-w1-c302-t2",
        "author_user_key": "u30208",
        "category": "회고",
        "post_title": "청크 실험 회고",
        "content": "검색 품질은 모델보다 데이터 정리 방식의 영향을 많이 받았습니다. 다음에는 카테고리별로 다른 query를 써보면 좋겠습니다.",
        "created_at": "2026-06-04T18:45:00+00:00",
    },
    {
        "key": "post-w1-c303-t1-study",
        "board_key": "board-w1-c303-t1",
        "author_user_key": "u30301",
        "category": "학습 기록",
        "post_title": "서비스 레이어 분리",
        "content": "API 라우터에서 바로 벡터DB를 호출하지 않고 rag_service를 따로 두는 방향으로 정리했습니다. 테스트도 이 편이 더 쉬울 것 같습니다.",
        "created_at": "2026-06-05T09:10:00+00:00",
    },
    {
        "key": "post-w1-c303-t1-question",
        "board_key": "board-w1-c303-t1",
        "author_user_key": "u30303",
        "category": "질문",
        "post_title": "요약 API는 저장형이 좋을까 실시간이 좋을까",
        "content": "주간 요약은 비용이 있으니 저장형이 좋아 보입니다. 다만 게시글이 수정되면 요약을 다시 만들어야 하는 조건이 필요합니다.",
        "created_at": "2026-06-05T14:20:00+00:00",
    },
    {
        "key": "post-w1-c303-t1-retro",
        "board_key": "board-w1-c303-t1",
        "author_user_key": "u30304",
        "category": "회고",
        "post_title": "작업 범위 조절 회고",
        "content": "처음에 기능 범위를 크게 잡았지만, 게시글 검색과 주간 요약을 먼저 연결하는 방향으로 줄이니 진행이 빨라졌습니다.",
        "created_at": "2026-06-05T18:40:00+00:00",
    },
    {
        "key": "post-w1-c303-t2-study",
        "board_key": "board-w1-c303-t2",
        "author_user_key": "u30307",
        "category": "학습 기록",
        "post_title": "벡터 인덱스 동기화 흐름",
        "content": "게시글 생성 시 index_post, 수정 시 reindex_post, 삭제 시 delete_vectors를 호출하는 흐름으로 정리했습니다.",
        "created_at": "2026-06-06T10:15:00+00:00",
    },
    {
        "key": "post-w1-c303-t2-question",
        "board_key": "board-w1-c303-t2",
        "author_user_key": "u30306",
        "category": "질문",
        "post_title": "학생 프로필 검색은 팀 추천 전에만 하면 될까",
        "content": "팀 추천 이후에도 운영자가 조정할 때 학생 프로필 근거를 다시 보여주면 좋을 것 같습니다.",
        "created_at": "2026-06-06T13:35:00+00:00",
    },
    {
        "key": "post-w1-c303-t2-retro",
        "board_key": "board-w1-c303-t2",
        "author_user_key": "u30305",
        "category": "회고",
        "post_title": "근거 표시 방식 회고",
        "content": "AI 추천 이유만 보여주면 신뢰하기 어렵고, 어떤 자기소개나 게시글을 근거로 삼았는지 함께 보여줘야 설득력이 생깁니다.",
        "created_at": "2026-06-06T19:10:00+00:00",
    },
]

COMMENTS = [
    {"post_key": "post-w1-c301-t1-study", "author_user_key": "u30104", "content": "metadata에 classroom과 team_num도 넣으면 운영자 화면에서 필터링하기 쉬울 것 같습니다.", "created_at": "2026-06-01T10:05:00+00:00"},
    {"post_key": "post-w1-c301-t1-question", "author_user_key": "u30101", "content": "수정 이벤트에서는 기존 vector_doc_id를 조회한 뒤 삭제하고 다시 넣는 쪽이 단순해 보입니다.", "created_at": "2026-06-01T15:00:00+00:00"},
    {"post_key": "post-w1-c301-t1-retro", "author_user_key": "u30103", "content": "회의 결정 사항을 게시글로 남기는 방식에 동의합니다. 다음부터 체크리스트도 같이 남기겠습니다.", "created_at": "2026-06-01T19:00:00+00:00"},
    {"post_key": "post-w1-c301-t2-study", "author_user_key": "u30105", "content": "category 필터를 걸면 질문과 회고가 섞이는 문제가 줄어드는지 더 확인해봅시다.", "created_at": "2026-06-02T10:40:00+00:00"},
    {"post_key": "post-w1-c301-t2-question", "author_user_key": "u30108", "content": "회고는 요약에는 필요하고 일반 Q&A 검색에서는 낮은 우선순위로 두면 좋겠습니다.", "created_at": "2026-06-02T16:00:00+00:00"},
    {"post_key": "post-w1-c301-t2-retro", "author_user_key": "u30107", "content": "다음 실험에서는 원문 청크를 같이 출력해서 왜 검색됐는지 확인해보겠습니다.", "created_at": "2026-06-02T19:30:00+00:00"},
    {"post_key": "post-w1-c302-t1-study", "author_user_key": "u30203", "content": "목록 API와 상세 API를 분리하면 프론트도 다루기 편할 것 같습니다.", "created_at": "2026-06-03T10:20:00+00:00"},
    {"post_key": "post-w1-c302-t1-question", "author_user_key": "u30201", "content": "댓글 검색 결과에는 부모 게시글 제목을 같이 붙여서 LLM에 넘기면 맥락이 보완될 것 같습니다.", "created_at": "2026-06-03T14:05:00+00:00"},
    {"post_key": "post-w1-c302-t1-retro", "author_user_key": "u30204", "content": "필드가 줄어드니 테스트 데이터도 만들기 쉬워졌습니다.", "created_at": "2026-06-03T18:40:00+00:00"},
    {"post_key": "post-w1-c302-t2-study", "author_user_key": "u30206", "content": "요약용과 검색용 청크 크기를 다르게 가져갈 수 있는지도 확인해보면 좋겠습니다.", "created_at": "2026-06-04T11:15:00+00:00"},
    {"post_key": "post-w1-c302-t2-question", "author_user_key": "u30205", "content": "MVP에서는 없어도 되지만, 재색인 최적화할 때 content_hash가 유용할 것 같습니다.", "created_at": "2026-06-04T14:35:00+00:00"},
    {"post_key": "post-w1-c302-t2-retro", "author_user_key": "u30207", "content": "카테고리별 query template을 따로 두는 방식도 괜찮아 보입니다.", "created_at": "2026-06-04T19:20:00+00:00"},
    {"post_key": "post-w1-c303-t1-study", "author_user_key": "u30303", "content": "rag_service를 분리하면 mock으로 테스트하기 쉬워질 것 같습니다.", "created_at": "2026-06-05T09:55:00+00:00"},
    {"post_key": "post-w1-c303-t1-question", "author_user_key": "u30301", "content": "저장형으로 만들고, 게시글 수정 시 summary_stale 같은 상태를 둘 수도 있겠습니다.", "created_at": "2026-06-05T15:00:00+00:00"},
    {"post_key": "post-w1-c303-t1-retro", "author_user_key": "u30302", "content": "이번 주 목표를 작게 줄인 것이 효과적이었습니다.", "created_at": "2026-06-05T19:15:00+00:00"},
    {"post_key": "post-w1-c303-t2-study", "author_user_key": "u30308", "content": "삭제 흐름은 DB 삭제와 벡터 삭제 순서를 명확히 정해야 할 것 같습니다.", "created_at": "2026-06-06T10:50:00+00:00"},
    {"post_key": "post-w1-c303-t2-question", "author_user_key": "u30307", "content": "운영자가 학생을 이동할 때도 근거 검색을 다시 보여주면 좋겠습니다.", "created_at": "2026-06-06T14:20:00+00:00"},
    {"post_key": "post-w1-c303-t2-retro", "author_user_key": "u30306", "content": "추천 이유와 근거 원문을 같이 보여주는 UI가 필요해 보입니다.", "created_at": "2026-06-06T19:45:00+00:00"},
]

WEEKLY_SUMMARIES = [
    {
        "team_key": "w1-c301-t1",
        "week": 1,
        "summary": "그린필드는 RAG 검색 API의 기본 구조와 Document metadata 설계를 정리했습니다. 게시글 수정 시 벡터 문서를 어떻게 갱신할지 논의했습니다.",
        "keywords": ["RAG", "Document", "metadata", "vector_doc_id"],
        "frequent_questions": ["게시글 수정 시 기존 벡터 문서를 삭제해야 하나요?", "metadata에는 어떤 값을 넣어야 하나요?"],
        "blocked_points": ["벡터 문서 갱신 정책", "검색 결과 출처 표시"],
        "recommended_materials": ["LangChain Document 문서", "Chroma metadata filter 예제"],
    },
    {
        "team_key": "w1-c301-t2",
        "week": 1,
        "summary": "벡터웨이는 Chroma metadata filter와 회고 데이터 인덱싱 여부를 실험했습니다. 검색 결과 디버깅 시 원문 청크 확인이 중요하다는 결론을 냈습니다.",
        "keywords": ["Chroma", "metadata filter", "회고", "검색 품질"],
        "frequent_questions": ["회고 글도 RAG에 넣어야 하나요?", "카테고리 필터가 검색 품질에 얼마나 영향을 주나요?"],
        "blocked_points": ["회고 데이터 우선순위", "검색 결과 디버깅 방식"],
        "recommended_materials": ["Chroma filtering guide", "RAG evaluation checklist"],
    },
    {
        "team_key": "w1-c302-t1",
        "week": 1,
        "summary": "로그북은 게시판 API 응답 구조와 댓글 인덱싱 방식을 정리했습니다. 목록 API와 상세 API를 분리하는 방향으로 합의했습니다.",
        "keywords": ["게시판 API", "댓글", "응답 구조", "상세 조회"],
        "frequent_questions": ["댓글도 별도 Document로 저장해야 하나요?", "목록 API에는 어떤 필드만 내려줘야 하나요?"],
        "blocked_points": ["댓글 검색 맥락 부족", "응답 필드 범위"],
        "recommended_materials": ["FastAPI response model", "REST API pagination pattern"],
    },
    {
        "team_key": "w1-c302-t2",
        "week": 1,
        "summary": "리트리버는 청크 크기와 RagDocument 추적 필드를 비교했습니다. MVP에서는 단순 재색인을 우선하고, 이후 content_hash 최적화를 검토하기로 했습니다.",
        "keywords": ["chunking", "RagDocument", "content_hash", "재색인"],
        "frequent_questions": ["content_hash가 꼭 필요한가요?", "요약용과 검색용 청크 크기를 다르게 둬야 하나요?"],
        "blocked_points": ["청크 크기 기준", "재색인 최적화 범위"],
        "recommended_materials": ["Text splitter 전략", "Vector index lifecycle 문서"],
    },
    {
        "team_key": "w1-c303-t1",
        "week": 1,
        "summary": "컨텍스트는 RAG 서비스 레이어 분리와 주간 요약 저장 방식을 논의했습니다. 비용과 응답 속도를 고려해 저장형 요약을 우선하기로 했습니다.",
        "keywords": ["service layer", "weekly summary", "저장형 요약", "테스트"],
        "frequent_questions": ["요약 API는 실시간이 좋나요 저장형이 좋나요?", "게시글 수정 후 요약은 어떻게 처리하나요?"],
        "blocked_points": ["요약 갱신 조건", "서비스 레이어 테스트"],
        "recommended_materials": ["Service layer pattern", "FastAPI dependency override 테스트"],
    },
    {
        "team_key": "w1-c303-t2",
        "week": 1,
        "summary": "메타데이터는 벡터 인덱스 동기화와 팀 추천 근거 표시 방식을 정리했습니다. AI 추천 이유와 근거 원문을 함께 보여줘야 신뢰도가 높아진다는 결론을 냈습니다.",
        "keywords": ["vector sync", "team matching", "근거 표시", "source tracking"],
        "frequent_questions": ["학생 프로필 검색은 팀 추천 전에만 하면 되나요?", "추천 이유에 근거 원문을 어떻게 연결하나요?"],
        "blocked_points": ["벡터 삭제 순서", "추천 근거 UI"],
        "recommended_materials": ["Source citation UI pattern", "RAG source tracking 설계"],
    },
]

EXPECTED_USER_COUNT = len(USERS)
EXPECTED_STUDENT_PROFILE_COUNT = len(STUDENT_PROFILES)
EXPECTED_TEAM_COUNT = len(TEAMS)
EXPECTED_TEAM_MEMBER_COUNT = len(TEAM_MEMBERS)
EXPECTED_BOARD_COUNT = len(BOARDS)
EXPECTED_POST_COUNT = len(POSTS)
EXPECTED_COMMENT_COUNT = len(COMMENTS)
EXPECTED_WEEKLY_SUMMARY_COUNT = len(WEEKLY_SUMMARIES)
